<?xml version="1.0" encoding="utf-8"?>
<Project>
  <!-- This file prevents parent Directory.Build.props from being imported -->
  <!-- We don't want the default TargetFrameworks for this test project -->
  <PropertyGroup>
    <DebugType>portable</DebugType>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>

